spring:
  application:
    name: wallet_system
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha
