spring:
  application:
    name: wallet_system
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, email, profile
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  messages:
    basename: messages
    encoding: UTF-8
  sql:
    init:
      mode: always
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.side_project.wallet_system: DEBUG
  file:
    name: logs/wallet-system.log

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    url: /openapi.yaml
    disable-swagger-default-url: true
    operations-sorter: method
    tags-sorter: alpha